# Generated by Django 5.2.7 on 2025-11-16 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='manual',
            field=models.BooleanField(default=False),
        ),
    ]
