# Generated by Django 5.2.7 on 2025-11-16 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_workout_manual'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='performed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
