# Generated by Django 5.2.7 on 2025-11-16 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0003_workout_performed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='gpx_file',
            field=models.FileField(blank=True, null=True, upload_to='gpx/'),
        ),
    ]
