# Generated by Django 5.2.7 on 2025-12-03 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0007_remove_workout_gpx_file'),
    ]

    # Align Django's model state without performing a DB drop again.
    # This prevents makemigrations from re-generating RemoveField in future runs.
    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RemoveField(
                    model_name='workout',
                    name='gpx_file',
                ),
            ],
        ),
    ]
