# Generated by Django 5.2.7 on 2025-12-03 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_postreaction'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql='DROP TABLE IF EXISTS social_postlike CASCADE',
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.DeleteModel(
                    name='PostLike',
                ),
            ],
        ),
    ]
