# Generated by Django 5.2.7 on 2025-12-03 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_postreaction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostLike',
        ),
    ]
