# Generated by Django 5.2.7 on 2025-11-22 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_height_cm_userprofile_weight_kg'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='username_finalized',
            field=models.BooleanField(default=False),
        ),
    ]
