# Generated by Django 5.2.7 on 2025-11-22 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userprofile_username_finalized'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='strava_athlete_id',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
